title: Affective Computational Psychology Conference Deadlines
description: Countdown timers for affective science, computational psychology, CHI/HCI, emotion-aware computing and related conferences

author: yayunZ   # name

url: "https://yuliya-zzz.github.io"
baseurl: "/affective-comp-psych-deadlines"   

timezone: AoE   

markdown: kramdown
highlighter: rouge

theme: null   

plugins:
  - jekyll-feed

include:
  - '_pages'

# optional: if you have google analysis, or, empty
ga_id:


# github_username: yuliya-zzZ
# github_repo: affective-comp-psych-deadlines
