title: Affective Computational Psychology Conference Deadlines
description: Countdown timers for affective science, computational psychology, CHI/HCI, emotion-aware computing and related conferences
author: yayunZ

url: "https://yuliya-zzz.github.io"
baseurl: "/affective-comp-psych-deadlines"

# Jekyll setting
markdown: kramdown
highlighter: rouge

theme: null
plugins:
  - jekyll-feed
  
# optional: if have google analytics, or, keep empty
ga_id:

include: ['_pages']

twitter_hashtag: mlciv_jiessie
github_username: yuliya-zzZ
github_repo: affective-comp-psych-deadlines
